name: build

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run bootstrap
      - run: npm run test
  canary-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Canary Release
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm run release-canary
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
