name: build

on:
  pull_request:
    branches-ignore: [documentation, gh-pages]
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run bootstrap
      - run: npm run test
  canary-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm run bootstrap
      - name: Canary Release
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}' >> .npmrc
          npm run release-canary
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  stable-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm run bootstrap
      - name: Stable Release
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}' >> .npmrc
          npm run release
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
