name: Quality

on:
  pull_request: ~
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run lint
    - run: npm run check-license
    - run: npm run audit

  alpha-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [tests, checks]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Publish new alpha release
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPMJS_ACCESS_TOKEN}' >> .npmrc
          npm run release-canary
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
