name: build

on:
  pull_request: ~
  push:
    branches: [master]
  release:
    types: [created]


jobs:
  # tests:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macos-latest, windows-latest, ubuntu-latest]
  #       node-version: [10.x, 12.x]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - run: npm run test

  # checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: '12.x'
  #   - run: npm ci
  #   - run: npm run lint
  #     name: Static Code Check
  #   - run: npx license-checker
  #   - run: npx license-checker --onlyAllow "MIT;Apache;ISC;BSD;WTFPL;Artistic;CC-BY;CC0;Unlicense"
  #     name: License Check
  #   - run: npx audit-ci -m
  #     name: Dependency Vulnerability Check

  canary-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    # needs: [tests, checks]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: git status
      - name: Canary Release
        run: |
          git update-index --assume-unchanged .npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          git status
          npx lerna publish --canary -y

        env:
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Release
        run: |
          git update-index --assume-unchanged .npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npx lerna publish from-package -y
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

