name: Master Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [10.x, 12.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        node --version
        npm run bootstrap
        ls node_modules
    - name: Transpile
      run: npm run transpile
    - name: Test
      run: npm run test
    - name: Lint
      run: npm run lint
    - name: License check
      run: npm run check-license
    - name: CI audit
      run: npm run ci-audit
    - name: Publish canary
      run: |
        echo '//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}' >> .npmrc
        npm run release-canary
      env:
        NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
